os: linux
dist: focal
language: python
python: "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc g++ cmake
  - pip install conan

script:
  - mkdir build && cd build/
  - conan workspace install ../conanws.yml
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

