name: clockify_cli
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: "Setup"
        run: pip install conan && mkdir build

      - name: "Build artifacts"
        working-directory: ./build
        run: |
          conan workspace install ../conanws.yml
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
